baseURL = "http://www.23ro.de"
languageCode = "en-en"
title = "23Ro's Digest"
theme = "after-dark"

[caches]
    [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = -1

key = "AIzaSyBZEomtIf7jODJZpboI_HOQJHjTBmQKl_A"
googleAnalytics = "UA-117425007-1"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "post"
  url = "/posts/"
[[menu.main]]
  name = "About 23Ro"
  weight = 3
  identifier = "About"
  url = "/about/"
[[menu.main]]
  name = "Photography"
  weight = 4
  identifier = "Photography"
  url = "https://23ro.photography/"
[[menu.main]]
  name = "New Thread"
  weight = 5
  identifier = "New Thread"
  url = "https://new-thread.tech/"
[[menu.main]]
  name = "Legal Disclaimer"
  weight = 6
  identifier = "Legal Disclaimer"
  url = "/legal/"