baseURL = "http://www.23ro.de"
languageCode = "en-en"
title = "23Ro's Digest"
theme = "after-dark"
key = "AIzaSyBZEomtIf7jODJZpboI_HOQJHjTBmQKl_A"
googleAnalytics = "UA-117425007-1"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "post"
  url = "/posts/"
[[menu.main]]
  name = "About 23Ro"
  weight = 3
  identifier = "About"
  url = "/about/"
  [[menu.main]]
  name = "Legal Disclaimer"
  weight = 4
  identifier = "Legal Disclaimer"
  url = "/legal/"